# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Code/C++/CoordinateTransformer+

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Code/C++/CoordinateTransformer+

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Code/C++/CoordinateTransformer+/CMakeFiles /mnt/d/Code/C++/CoordinateTransformer+/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Code/C++/CoordinateTransformer+/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CoordinateTransformer

# Build rule for target.
CoordinateTransformer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CoordinateTransformer
.PHONY : CoordinateTransformer

# fast build rule for target.
CoordinateTransformer/fast:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/build
.PHONY : CoordinateTransformer/fast

CoordinateBuilder.o: CoordinateBuilder.cpp.o

.PHONY : CoordinateBuilder.o

# target to build an object file
CoordinateBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/CoordinateBuilder.cpp.o
.PHONY : CoordinateBuilder.cpp.o

CoordinateBuilder.i: CoordinateBuilder.cpp.i

.PHONY : CoordinateBuilder.i

# target to preprocess a source file
CoordinateBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/CoordinateBuilder.cpp.i
.PHONY : CoordinateBuilder.cpp.i

CoordinateBuilder.s: CoordinateBuilder.cpp.s

.PHONY : CoordinateBuilder.s

# target to generate assembly for a file
CoordinateBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/CoordinateBuilder.cpp.s
.PHONY : CoordinateBuilder.cpp.s

CoordinateTransformer+.o: CoordinateTransformer+.cpp.o

.PHONY : CoordinateTransformer+.o

# target to build an object file
CoordinateTransformer+.cpp.o:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/CoordinateTransformer+.cpp.o
.PHONY : CoordinateTransformer+.cpp.o

CoordinateTransformer+.i: CoordinateTransformer+.cpp.i

.PHONY : CoordinateTransformer+.i

# target to preprocess a source file
CoordinateTransformer+.cpp.i:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/CoordinateTransformer+.cpp.i
.PHONY : CoordinateTransformer+.cpp.i

CoordinateTransformer+.s: CoordinateTransformer+.cpp.s

.PHONY : CoordinateTransformer+.s

# target to generate assembly for a file
CoordinateTransformer+.cpp.s:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/CoordinateTransformer+.cpp.s
.PHONY : CoordinateTransformer+.cpp.s

DataTransformerBase.o: DataTransformerBase.cpp.o

.PHONY : DataTransformerBase.o

# target to build an object file
DataTransformerBase.cpp.o:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/DataTransformerBase.cpp.o
.PHONY : DataTransformerBase.cpp.o

DataTransformerBase.i: DataTransformerBase.cpp.i

.PHONY : DataTransformerBase.i

# target to preprocess a source file
DataTransformerBase.cpp.i:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/DataTransformerBase.cpp.i
.PHONY : DataTransformerBase.cpp.i

DataTransformerBase.s: DataTransformerBase.cpp.s

.PHONY : DataTransformerBase.s

# target to generate assembly for a file
DataTransformerBase.cpp.s:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/DataTransformerBase.cpp.s
.PHONY : DataTransformerBase.cpp.s

PointTransformer.o: PointTransformer.cpp.o

.PHONY : PointTransformer.o

# target to build an object file
PointTransformer.cpp.o:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/PointTransformer.cpp.o
.PHONY : PointTransformer.cpp.o

PointTransformer.i: PointTransformer.cpp.i

.PHONY : PointTransformer.i

# target to preprocess a source file
PointTransformer.cpp.i:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/PointTransformer.cpp.i
.PHONY : PointTransformer.cpp.i

PointTransformer.s: PointTransformer.cpp.s

.PHONY : PointTransformer.s

# target to generate assembly for a file
PointTransformer.cpp.s:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/PointTransformer.cpp.s
.PHONY : PointTransformer.cpp.s

RasterDataTransformer.o: RasterDataTransformer.cpp.o

.PHONY : RasterDataTransformer.o

# target to build an object file
RasterDataTransformer.cpp.o:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/RasterDataTransformer.cpp.o
.PHONY : RasterDataTransformer.cpp.o

RasterDataTransformer.i: RasterDataTransformer.cpp.i

.PHONY : RasterDataTransformer.i

# target to preprocess a source file
RasterDataTransformer.cpp.i:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/RasterDataTransformer.cpp.i
.PHONY : RasterDataTransformer.cpp.i

RasterDataTransformer.s: RasterDataTransformer.cpp.s

.PHONY : RasterDataTransformer.s

# target to generate assembly for a file
RasterDataTransformer.cpp.s:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/RasterDataTransformer.cpp.s
.PHONY : RasterDataTransformer.cpp.s

UsefulKit.o: UsefulKit.cpp.o

.PHONY : UsefulKit.o

# target to build an object file
UsefulKit.cpp.o:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/UsefulKit.cpp.o
.PHONY : UsefulKit.cpp.o

UsefulKit.i: UsefulKit.cpp.i

.PHONY : UsefulKit.i

# target to preprocess a source file
UsefulKit.cpp.i:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/UsefulKit.cpp.i
.PHONY : UsefulKit.cpp.i

UsefulKit.s: UsefulKit.cpp.s

.PHONY : UsefulKit.s

# target to generate assembly for a file
UsefulKit.cpp.s:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/UsefulKit.cpp.s
.PHONY : UsefulKit.cpp.s

VectorDataTransformer.o: VectorDataTransformer.cpp.o

.PHONY : VectorDataTransformer.o

# target to build an object file
VectorDataTransformer.cpp.o:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/VectorDataTransformer.cpp.o
.PHONY : VectorDataTransformer.cpp.o

VectorDataTransformer.i: VectorDataTransformer.cpp.i

.PHONY : VectorDataTransformer.i

# target to preprocess a source file
VectorDataTransformer.cpp.i:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/VectorDataTransformer.cpp.i
.PHONY : VectorDataTransformer.cpp.i

VectorDataTransformer.s: VectorDataTransformer.cpp.s

.PHONY : VectorDataTransformer.s

# target to generate assembly for a file
VectorDataTransformer.cpp.s:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/VectorDataTransformer.cpp.s
.PHONY : VectorDataTransformer.cpp.s

_Matrix.o: _Matrix.cpp.o

.PHONY : _Matrix.o

# target to build an object file
_Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/_Matrix.cpp.o
.PHONY : _Matrix.cpp.o

_Matrix.i: _Matrix.cpp.i

.PHONY : _Matrix.i

# target to preprocess a source file
_Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/_Matrix.cpp.i
.PHONY : _Matrix.cpp.i

_Matrix.s: _Matrix.cpp.s

.PHONY : _Matrix.s

# target to generate assembly for a file
_Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/_Matrix.cpp.s
.PHONY : _Matrix.cpp.s

stdafx.o: stdafx.cpp.o

.PHONY : stdafx.o

# target to build an object file
stdafx.cpp.o:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/stdafx.cpp.o
.PHONY : stdafx.cpp.o

stdafx.i: stdafx.cpp.i

.PHONY : stdafx.i

# target to preprocess a source file
stdafx.cpp.i:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/stdafx.cpp.i
.PHONY : stdafx.cpp.i

stdafx.s: stdafx.cpp.s

.PHONY : stdafx.s

# target to generate assembly for a file
stdafx.cpp.s:
	$(MAKE) -f CMakeFiles/CoordinateTransformer.dir/build.make CMakeFiles/CoordinateTransformer.dir/stdafx.cpp.s
.PHONY : stdafx.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CoordinateTransformer"
	@echo "... CoordinateBuilder.o"
	@echo "... CoordinateBuilder.i"
	@echo "... CoordinateBuilder.s"
	@echo "... CoordinateTransformer+.o"
	@echo "... CoordinateTransformer+.i"
	@echo "... CoordinateTransformer+.s"
	@echo "... DataTransformerBase.o"
	@echo "... DataTransformerBase.i"
	@echo "... DataTransformerBase.s"
	@echo "... PointTransformer.o"
	@echo "... PointTransformer.i"
	@echo "... PointTransformer.s"
	@echo "... RasterDataTransformer.o"
	@echo "... RasterDataTransformer.i"
	@echo "... RasterDataTransformer.s"
	@echo "... UsefulKit.o"
	@echo "... UsefulKit.i"
	@echo "... UsefulKit.s"
	@echo "... VectorDataTransformer.o"
	@echo "... VectorDataTransformer.i"
	@echo "... VectorDataTransformer.s"
	@echo "... _Matrix.o"
	@echo "... _Matrix.i"
	@echo "... _Matrix.s"
	@echo "... stdafx.o"
	@echo "... stdafx.i"
	@echo "... stdafx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

